### ISSUE TITLE
Cxx compiling error with julia-4.0 and LLVM-3.8  

### ISSUE THREAD

**Issue by ibadami** [Keno/Cxx.jl#159]
I am creating a new issue for this error.
I have installed julia-0.4 with the fix you provided https://github.com/JuliaLang/julia/pull/13150 for LLVM-3.8 in files cgutils.cpp and codegen.cpp. The installation is done successfully. But when I try to build Cxx package with that. I get the following errors.

```
julia> ENV["VERBOSE"]=1
1

julia> Pkg.build("Cxx")
INFO: Building Cxx
Tuning for julia installation at: /home/badami/Library/julia/usr/bin
 g++ -m64 -fno-rtti -DLIBRARY_EXPORTS -fPIC -O0 -g -std=c++11   -I/home/badami/Library/julia/usr/bin/../../usr/include -I/home/badami/Library/julia/usr/bin/../../src/support -I/home/badami/Library/julia/usr/include -I/home/badami/Library/julia/usr/bin/../../deps/llvm-svn/tools/clang/lib -c ../src/bootstrap.cpp -o build/bootstrap.o
../src/bootstrap.cpp: In function ‘void ReplaceFunctionForDecl(CxxInstance*, clang::FunctionDecl*, llvm::Function*)’:
../src/bootstrap.cpp:433:61: error: no matching function for call to ‘InlineFunction(llvm::cast_retty<llvm::CallInst, llvm::User*>::ret_type, llvm::InlineFunctionInfo&, bool)’
       llvm::InlineFunction(cast<llvm::CallInst>(*I),IFI,true);
                                                             ^
../src/bootstrap.cpp:433:61: note: candidates are:
In file included from ../src/bootstrap.cpp:15:0:
/home/badami/Library/julia/usr/bin/../../usr/include/llvm/Transforms/Utils/Cloning.h:237:6: note: bool llvm::InlineFunction(llvm::CallInst*, llvm::InlineFunctionInfo&, llvm::AAResults*, bool)
 bool InlineFunction(CallInst *C, InlineFunctionInfo &IFI,
      ^
/home/badami/Library/julia/usr/bin/../../usr/include/llvm/Transforms/Utils/Cloning.h:237:6: note:   no known conversion for argument 3 from ‘bool’ to ‘llvm::AAResults*’
/home/badami/Library/julia/usr/bin/../../usr/include/llvm/Transforms/Utils/Cloning.h:239:6: note: bool llvm::InlineFunction(llvm::InvokeInst*, llvm::InlineFunctionInfo&, llvm::AAResults*, bool)
 bool InlineFunction(InvokeInst *II, InlineFunctionInfo &IFI,
      ^
/home/badami/Library/julia/usr/bin/../../usr/include/llvm/Transforms/Utils/Cloning.h:239:6: note:   no known conversion for argument 1 from ‘llvm::cast_retty<llvm::CallInst, llvm::User*>::ret_type {aka llvm::CallInst*}’ to ‘llvm::InvokeInst*’
/home/badami/Library/julia/usr/bin/../../usr/include/llvm/Transforms/Utils/Cloning.h:241:6: note: bool llvm::InlineFunction(llvm::CallSite, llvm::InlineFunctionInfo&, llvm::AAResults*, bool)
 bool InlineFunction(CallSite CS, InlineFunctionInfo &IFI,
      ^
/home/badami/Library/julia/usr/bin/../../usr/include/llvm/Transforms/Utils/Cloning.h:241:6: note:   no known conversion for argument 3 from ‘bool’ to ‘llvm::AAResults*’
../src/bootstrap.cpp: In function ‘void cleanup_cpp_env(CxxInstance*, cppcall_state_t*)’:
../src/bootstrap.cpp:986:27: error: no match for ‘operator=’ (operand types are ‘clang::CodeGen::Address’ and ‘std::nullptr_t’)
     Cxx->CGF->ReturnValue = nullptr;
                           ^
../src/bootstrap.cpp:986:27: note: candidates are:
In file included from /home/badami/Library/julia/usr/bin/../../deps/llvm-svn/tools/clang/lib/CodeGen/CGValue.h:22:0,
                 from /home/badami/Library/julia/usr/bin/../../deps/llvm-svn/tools/clang/lib/CodeGen/CGCall.h:18,
                 from /home/badami/Library/julia/usr/bin/../../deps/llvm-svn/tools/clang/lib/CodeGen/CodeGenTypes.h:17,
                 from /home/badami/Library/julia/usr/bin/../../deps/llvm-svn/tools/clang/lib/CodeGen/CodeGenModule.h:19,
                 from ../src/bootstrap.cpp:54:
/home/badami/Library/julia/usr/bin/../../deps/llvm-svn/tools/clang/lib/CodeGen/Address.h:25:7: note: clang::CodeGen::Address& clang::CodeGen::Address::operator=(const clang::CodeGen::Address&)
 class Address {
       ^
/home/badami/Library/julia/usr/bin/../../deps/llvm-svn/tools/clang/lib/CodeGen/Address.h:25:7: note:   no known conversion for argument 1 from ‘std::nullptr_t’ to ‘const clang::CodeGen::Address&’
/home/badami/Library/julia/usr/bin/../../deps/llvm-svn/tools/clang/lib/CodeGen/Address.h:25:7: note: clang::CodeGen::Address& clang::CodeGen::Address::operator=(clang::CodeGen::Address&&)
/home/badami/Library/julia/usr/bin/../../deps/llvm-svn/tools/clang/lib/CodeGen/Address.h:25:7: note:   no known conversion for argument 1 from ‘std::nullptr_t’ to ‘clang::CodeGen::Address&&’
../src/bootstrap.cpp: In function ‘void AssociateValue(CxxInstance*, clang::Decl*, void*, llvm::Value*)’:
../src/bootstrap.cpp:1109:81: error: no matching function for call to ‘clang::CodeGen::CodeGenFunction::EmitParmDecl(clang::VarDecl&, llvm::Value*, bool, int)’
     Cxx->CGF->EmitParmDecl(*vd, Cxx->CGF->Builder.CreateBitCast(V, Ty), false, 0);
                                                                                 ^
../src/bootstrap.cpp:1109:81: note: candidate is:
In file included from ../src/bootstrap.cpp:57:0:
/home/badami/Library/julia/usr/bin/../../deps/llvm-svn/tools/clang/lib/CodeGen/CodeGenFunction.h:2088:8: note: void clang::CodeGen::CodeGenFunction::EmitParmDecl(const clang::VarDecl&, clang::CodeGen::CodeGenFunction::ParamValue, unsigned int)
   void EmitParmDecl(const VarDecl &D, ParamValue Arg, unsigned ArgNo);
        ^
/home/badami/Library/julia/usr/bin/../../deps/llvm-svn/tools/clang/lib/CodeGen/CodeGenFunction.h:2088:8: note:   candidate expects 3 arguments, 4 provided
../src/bootstrap.cpp: In function ‘void* emitcallexpr(CxxInstance*, clang::Expr*, llvm::Value*)’:
../src/bootstrap.cpp:1166:103: error: no matching function for call to ‘clang::CodeGen::ReturnValueSlot::ReturnValueSlot(llvm::Value*&, bool)’
     clang::CodeGen::RValue ret = Cxx->CGF->EmitCallExpr(CE,clang::CodeGen::ReturnValueSlot(rslot,false));
                                                                                                       ^
../src/bootstrap.cpp:1166:103: note: candidates are:
In file included from /home/badami/Library/julia/usr/bin/../../deps/llvm-svn/tools/clang/lib/CodeGen/CodeGenTypes.h:17:0,
                 from /home/badami/Library/julia/usr/bin/../../deps/llvm-svn/tools/clang/lib/CodeGen/CodeGenModule.h:19,
                 from ../src/bootstrap.cpp:54:
/home/badami/Library/julia/usr/bin/../../deps/llvm-svn/tools/clang/lib/CodeGen/CGCall.h:166:5: note: clang::CodeGen::ReturnValueSlot::ReturnValueSlot(clang::CodeGen::Address, bool, bool)
     ReturnValueSlot(Address Addr, bool IsVolatile, bool IsUnused = false)
     ^
/home/badami/Library/julia/usr/bin/../../deps/llvm-svn/tools/clang/lib/CodeGen/CGCall.h:166:5: note:   no known conversion for argument 1 from ‘llvm::Value*’ to ‘clang::CodeGen::Address’
/home/badami/Library/julia/usr/bin/../../deps/llvm-svn/tools/clang/lib/CodeGen/CGCall.h:165:5: note: clang::CodeGen::ReturnValueSlot::ReturnValueSlot()
     ReturnValueSlot() {}
     ^
/home/badami/Library/julia/usr/bin/../../deps/llvm-svn/tools/clang/lib/CodeGen/CGCall.h:165:5: note:   candidate expects 0 arguments, 2 provided
/home/badami/Library/julia/usr/bin/../../deps/llvm-svn/tools/clang/lib/CodeGen/CGCall.h:154:9: note: constexpr clang::CodeGen::ReturnValueSlot::ReturnValueSlot(const clang::CodeGen::ReturnValueSlot&)
   class ReturnValueSlot {
         ^
/home/badami/Library/julia/usr/bin/../../deps/llvm-svn/tools/clang/lib/CodeGen/CGCall.h:154:9: note:   candidate expects 1 argument, 2 provided
/home/badami/Library/julia/usr/bin/../../deps/llvm-svn/tools/clang/lib/CodeGen/CGCall.h:154:9: note: constexpr clang::CodeGen::ReturnValueSlot::ReturnValueSlot(clang::CodeGen::ReturnValueSlot&&)
/home/badami/Library/julia/usr/bin/../../deps/llvm-svn/tools/clang/lib/CodeGen/CGCall.h:154:9: note:   candidate expects 1 argument, 2 provided
../src/bootstrap.cpp:1170:18: error: ‘class clang::CodeGen::RValue’ has no member named ‘getAggregateAddr’
       return ret.getAggregateAddr();
                  ^
../src/bootstrap.cpp: In function ‘void emitexprtomem(CxxInstance*, clang::Expr*, llvm::Value*, int)’:
../src/bootstrap.cpp:1175:68: error: no matching function for call to ‘clang::CodeGen::CodeGenFunction::EmitAnyExprToMem(clang::Expr*&, llvm::Value*&, clang::Qualifiers, int&)’
     Cxx->CGF->EmitAnyExprToMem(E, addr, clang::Qualifiers(), isInit);
                                                                    ^
../src/bootstrap.cpp:1175:68: note: candidate is:
In file included from ../src/bootstrap.cpp:57:0:
/home/badami/Library/julia/usr/bin/../../deps/llvm-svn/tools/clang/lib/CodeGen/CodeGenFunction.h:1664:8: note: void clang::CodeGen::CodeGenFunction::EmitAnyExprToMem(const clang::Expr*, clang::CodeGen::Address, clang::Qualifiers, bool)
   void EmitAnyExprToMem(const Expr *E, Address Location,
        ^
/home/badami/Library/julia/usr/bin/../../deps/llvm-svn/tools/clang/lib/CodeGen/CodeGenFunction.h:1664:8: note:   no known conversion for argument 2 from ‘llvm::Value*’ to ‘clang::CodeGen::Address’
../src/bootstrap.cpp: In function ‘void* EmitAnyExpr(CxxInstance*, clang::Expr*, llvm::Value*)’:
../src/bootstrap.cpp:1184:18: error: ‘class clang::CodeGen::RValue’ has no member named ‘getAggregateAddr’
       return ret.getAggregateAddr();
                  ^
../src/bootstrap.cpp: In function ‘void emitDestroyCXXObject(CxxInstance*, llvm::Value*, clang::Type*)’:
../src/bootstrap.cpp:1980:64: error: no matching function for call to ‘clang::CodeGen::CodeGenFunction::destroyCXXObject(clang::CodeGen::CodeGenFunction&, llvm::Value*&, clang::QualType)’
   Cxx->CGF->destroyCXXObject(*Cxx->CGF, x, clang::QualType(T,0));
                                                                ^
../src/bootstrap.cpp:1980:64: note: candidate is:
In file included from ../src/bootstrap.cpp:57:0:
/home/badami/Library/julia/usr/bin/../../deps/llvm-svn/tools/clang/lib/CodeGen/CodeGenFunction.h:1874:20: note: static void clang::CodeGen::CodeGenFunction::destroyCXXObject(clang::CodeGen::CodeGenFunction&, clang::CodeGen::Address, clang::QualType)
   static Destroyer destroyCXXObject;
                    ^
/home/badami/Library/julia/usr/bin/../../deps/llvm-svn/tools/clang/lib/CodeGen/CodeGenFunction.h:1874:20: note:   no known conversion for argument 2 from ‘llvm::Value*’ to ‘clang::CodeGen::Address’
make: *** [build/bootstrap.o] Error 1

[ ERROR: Cxx ]

LoadError: failed process: Process(`make -f BuildBootstrap.Makefile JULIA_HOME=/home/badami/Library/julia/usr/bin`, ProcessExited(2)) [2]
while loading /home/badami/.julia/v0.4/Cxx/deps/build.jl, in expression starting on line 16

[ BUILD ERRORS ]

WARNING: Cxx had build errors.

 - packages with build errors remain installed in /home/badami/.julia/v0.4
 - build the package(s) and all dependencies with `Pkg.build("Cxx")`
 - build a single package by running its `deps/build.jl` script
```

**Comment by cbecker** [comment]
@Keno do you think Cxx.jl will be working with Julia v0.4 by default? I am planning to switch to v0.4 by checking out release-0.4, but it is not meant to be compatible with the latest LLVM master. Do you have a suggestion of an alternative branch or commit to pull from to specify in Make.user? Thanks.

**Comment by ibadami** [comment]
I tried compiling Julia master with LLVM master and I do not get any
compilation error anymore. I didn't check julia-0.4 with LLVM master yet.

On Wed, Sep 23, 2015 at 11:37 AM, Carlos Becker <notifications@github.com>
wrote:

> @Keno <https://github.com/Keno> do you think Cxx.jl will be working with
> Julia v0.4 by default? I am planning to switch to v0.4 by checking out
> release-0.4, but it is not meant to be compatible with the latest LLVM
> master. Do you have a suggestion of an alternative branch or commit to pull
> from to specify in Make.user? Thanks.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Keno/Cxx.jl/issues/159#issuecomment-142546075>.
>



-- 

Ishrat Badami
Ph.D. Student
Computer Vision Group
UMIC Research Centre
RWTH Aachen University
Room No 129
Mies-van-der-Rohe Strasse 15
D-52074 Aachen
Germany
------------------------------------
Tel: +49 241 80 20775
Fax: +49 241 80 22731

e-mail: badami@vision.rwth-aachen.de
URL: http://www.vision.rwth-aachen.de/people/ishrat-badami
-----------------------------------------------------------------

**Comment by cbecker** [comment]
yes, indeed, master works fine. However that is tagged as v0.5 now, and I was trying to stick to v0.4.
