### ISSUE TITLE
julia compilation error

### ISSUE THREAD

**Issue by jingpengwu** [Keno/Cxx.jl#211]
I used the latest version of julia and compiled successfully.
after adding the Make.user file according to the Readme of Cxx, the compilation have the following error.

Previous fix for LLVM3.8 was merged, so this issue should be a new one?
https://github.com/JuliaLang/julia/commit/bcc3736d958324e26465fdd2e025e3808b21c8e6

llvm[4]: Compiling TargetMachine.cpp for Release+Asserts build
llvm[4]: Compiling TargetMachineC.cpp for Release+Asserts build
llvm[4]: Compiling TargetRecip.cpp for Release+Asserts build
llvm[4]: Compiling TargetSubtargetInfo.cpp for Release+Asserts build
llvm[4]: Building Release+Asserts Archive Library libLLVMTarget.a
llvm[3]: Compiling libllvm.cpp for Release+Asserts build (PIC)
llvm[3]: Linking Release+Asserts Shared Library libLLVM-3.8svn.so
/home/jingpeng_wu/julia/deps/build/llvm-svn/build_Release+Asserts/Release+Asserts/lib/libLLVMSupport.a(ThreadPool.o): In function std::future<std::result_of<std::function<void ()> ()>::type> std::async<std::function<void ()>>(std::launch, std::function<void ()>&&):
ThreadPool.cpp:(.text._ZSt5asyncISt8functionIFvvEEJEESt6futureINSt9result_ofIFT_DpT0_EE4typeEESt6launchOS5_DpOS6_[_ZSt5asyncISt8functionIFvvEEJEESt6futureINSt9result_ofIFT_DpT0_EE4typeEESt6launchOS5_DpOS6_]+0x31a): undefined reference to `pthread_create'
collect2: error: ld returned 1 exit status
/home/jingpeng_wu/julia/deps/srccache/llvm-svn/Makefile.rules:1209: recipe for target '/home/jingpeng_wu/julia/deps/build/llvm-svn/build_Release+Asserts/Release+Asserts/lib/libLLVM-3.8svn.so' failed
make[3]: *** [/home/jingpeng_wu/julia/deps/build/llvm-svn/build_Release+Asserts/Release+Asserts/lib/libLLVM-3.8svn.so] Error 1
/home/jingpeng_wu/julia/deps/srccache/llvm-svn/Makefile.rules:883: recipe for target 'all' failed
make[2]: *** [all] Error 1
Makefile:702: recipe for target 'build/llvm-svn/build_Release+Asserts/Release+Asserts/lib/libLLVMCodeGen.a' failed
make[1]: *** [build/llvm-svn/build_Release+Asserts/Release+Asserts/lib/libLLVMCodeGen.a] Error 2
Makefile:78: recipe for target 'julia-deps' failed
make: *** [julia-deps] Error 2

**Comment by jingpengwu** [comment]
I updated the code from this commit
https://github.com/llvm-mirror/llvm/commit/ae55d356be840aab2898f47a9c704e7a542f76c2
and rebuild the llvm, it seems that the llvm problem was solved. But there is another error..

```
    LINK src/support/libsupport.a
    CC src/flisp/flisp.o
    CC src/flisp/builtins.o
    CC src/flisp/equalhash.o
    CC src/flisp/table.o
    CC src/flisp/iostream.o
    CC src/flisp/string.o
    CC src/flisp/julia_extensions.o
    CC src/flisp/flmain.o
In file included from /home/jingpeng_wu/julia/src/codegen.cpp:190:0:
/home/jingpeng_wu/julia/src/jitlayers.cpp: In function ‘void addOptimizationPasses(T*)’:
/home/jingpeng_wu/julia/src/jitlayers.cpp:25:42: error: there are no arguments to ‘createTypeBasedAAWrapperPass’ that depend on a template parameter, so a declaration of ‘createTypeBasedAAWrapperPass’ must be available [-fpermissive]
     PM->add(createTypeBasedAAWrapperPass());
                                          ^
/home/jingpeng_wu/julia/src/jitlayers.cpp:25:42: note: (if you use ‘-fpermissive’, G++ will accept your code, but allowing the use of an undeclared name is deprecated)
/home/jingpeng_wu/julia/src/jitlayers.cpp:31:42: error: there are no arguments to ‘createBasicAAWrapperPass’ that depend on a template parameter, so a declaration of ‘createBasicAAWrapperPass’ must be available [-fpermissive]
         PM->add(createBasicAAWrapperPass());
                                          ^
In file included from /home/jingpeng_wu/julia/src/codegen.cpp:708:0:
/home/jingpeng_wu/julia/src/cgutils.cpp: In function ‘void jl_dump_shadow(char*, int, const char*, size_t, bool)’:
/home/jingpeng_wu/julia/src/cgutils.cpp:729:54: error: request for member ‘release’ in ‘llvm::CloneModule(((const llvm::Module*)shadow_module), VMap)’, which is of pointer type ‘llvm::Module*’ (maybe you meant to use ‘->’ ?)
     Module *clone = CloneModule(shadow_module, VMap).release();
                                                      ^
/home/jingpeng_wu/julia/src/codegen.cpp: In function ‘void jl_generate_fptr(jl_function_t*)’:
/home/jingpeng_wu/julia/src/codegen.cpp:1024:27: error: cannot declare variable ‘mover’ to be of abstract type ‘FunctionMover’
             FunctionMover mover(m, shadow_module);
                           ^
In file included from /home/jingpeng_wu/julia/src/codegen.cpp:708:0:
/home/jingpeng_wu/julia/src/cgutils.cpp:310:7: note:   because the following virtual functions are pure within ‘FunctionMover’:
 class FunctionMover : public ValueMaterializer
       ^
In file included from /home/jingpeng_wu/julia/usr/include/llvm/Transforms/Utils/Cloning.h:25:0,
                 from /home/jingpeng_wu/julia/src/codegen.cpp:79:
/home/jingpeng_wu/julia/usr/include/llvm/Transforms/Utils/ValueMapper.h:47:20: note: 	virtual llvm::Value* llvm::ValueMaterializer::materializeValueFor(llvm::Value*)
     virtual Value *materializeValueFor(Value *V) = 0;
                    ^
/home/jingpeng_wu/julia/src/codegen.cpp: In function ‘void* jl_function_ptr(jl_function_t*, jl_value_t*, jl_value_t*)’:
/home/jingpeng_wu/julia/src/codegen.cpp:1196:23: error: cannot declare variable ‘mover’ to be of abstract type ‘FunctionMover’
         FunctionMover mover(m, shadow_module);
                       ^
/home/jingpeng_wu/julia/src/codegen.cpp: In function ‘void jl_extern_c(jl_function_t*, jl_value_t*, jl_value_t*, char*)’:
/home/jingpeng_wu/julia/src/codegen.cpp:1233:90: error: no matching function for call to ‘llvm::GlobalAlias::create(llvm::Type*, unsigned int, llvm::GlobalValue::LinkageTypes, char*&, llvm::Function*&, llvm::Module*)’
                             GlobalValue::ExternalLinkage, name, llvmf, llvmf->getParent());
                                                                                          ^
In file included from /home/jingpeng_wu/julia/usr/include/llvm/IR/Module.h:22:0,
                 from /home/jingpeng_wu/julia/usr/include/llvm/ExecutionEngine/ExecutionEngine.h:22,
                 from /home/jingpeng_wu/julia/src/codegen.cpp:21:
/home/jingpeng_wu/julia/usr/include/llvm/IR/GlobalAlias.h:47:23: note: candidate: static llvm::GlobalAlias* llvm::GlobalAlias::create(llvm::PointerType*, llvm::GlobalValue::LinkageTypes, const llvm::Twine&, llvm::Constant*, llvm::Module*)
   static GlobalAlias *create(PointerType *Ty, LinkageTypes Linkage,
                       ^
/home/jingpeng_wu/julia/usr/include/llvm/IR/GlobalAlias.h:47:23: note:   candidate expects 5 arguments, 6 provided
/home/jingpeng_wu/julia/usr/include/llvm/IR/GlobalAlias.h:52:23: note: candidate: static llvm::GlobalAlias* llvm::GlobalAlias::create(llvm::PointerType*, llvm::GlobalValue::LinkageTypes, const llvm::Twine&, llvm::Module*)
   static GlobalAlias *create(PointerType *Ty, LinkageTypes Linkage,
                       ^
/home/jingpeng_wu/julia/usr/include/llvm/IR/GlobalAlias.h:52:23: note:   candidate expects 4 arguments, 6 provided
/home/jingpeng_wu/julia/usr/include/llvm/IR/GlobalAlias.h:56:23: note: candidate: static llvm::GlobalAlias* llvm::GlobalAlias::create(llvm::PointerType*, llvm::GlobalValue::LinkageTypes, const llvm::Twine&, llvm::GlobalValue*)
   static GlobalAlias *create(PointerType *Ty, LinkageTypes Linkage,
                       ^
/home/jingpeng_wu/julia/usr/include/llvm/IR/GlobalAlias.h:56:23: note:   candidate expects 4 arguments, 6 provided
/home/jingpeng_wu/julia/usr/include/llvm/IR/GlobalAlias.h:60:23: note: candidate: static llvm::GlobalAlias* llvm::GlobalAlias::create(llvm::GlobalValue::LinkageTypes, const llvm::Twine&, llvm::GlobalValue*)
   static GlobalAlias *create(LinkageTypes Linkage, const Twine &Name,
                       ^
/home/jingpeng_wu/julia/usr/include/llvm/IR/GlobalAlias.h:60:23: note:   candidate expects 3 arguments, 6 provided
/home/jingpeng_wu/julia/usr/include/llvm/IR/GlobalAlias.h:64:23: note: candidate: static llvm::GlobalAlias* llvm::GlobalAlias::create(const llvm::Twine&, llvm::GlobalValue*)
   static GlobalAlias *create(const Twine &Name, GlobalValue *Aliasee);
                       ^
/home/jingpeng_wu/julia/usr/include/llvm/IR/GlobalAlias.h:64:23: note:   candidate expects 2 arguments, 6 provided
In file included from /home/jingpeng_wu/julia/src/intrinsics.cpp:7:0,
                 from /home/jingpeng_wu/julia/src/codegen.cpp:1666:
/home/jingpeng_wu/julia/src/ccall.cpp: In function ‘jl_cgval_t emit_llvmcall(jl_value_t**, size_t, jl_codectx_t*)’:
/home/jingpeng_wu/julia/src/ccall.cpp:710:27: error: cannot declare variable ‘mover’ to be of abstract type ‘FunctionMover’
             FunctionMover mover(active_module,f->getParent());
                           ^
/home/jingpeng_wu/julia/src/ccall.cpp: In function ‘jl_cgval_t emit_ccall(jl_value_t**, size_t, jl_codectx_t*)’:
/home/jingpeng_wu/julia/src/ccall.cpp:1366:48: error: ‘class llvm::Instruction’ has no member named ‘getIterator’
                 instList.insertAfter(savespot->getIterator(), (Instruction*)stacksave);
                                                ^
/home/jingpeng_wu/julia/src/codegen.cpp: In function ‘void emit_function(jl_lambda_info_t*, jl_llvm_functions_t*, jl_llvm_functions_t*, jl_cyclectx_t*)’:
/home/jingpeng_wu/julia/src/codegen.cpp:4719:100: error: no matching function for call to ‘llvm::DIBuilder::createSubroutineType(llvm::DITypeRefArray)’
             subrty = ctx.dbuilder->createSubroutineType(ctx.dbuilder->getOrCreateTypeArray(ditypes));
                                                                                                    ^
In file included from /home/jingpeng_wu/julia/src/codegen.cpp:46:0:
/home/jingpeng_wu/julia/usr/include/llvm/IR/DIBuilder.h:383:23: note: candidate: llvm::DISubroutineType* llvm::DIBuilder::createSubroutineType(llvm::DIFile*, llvm::DITypeRefArray, unsigned int)
     DISubroutineType *createSubroutineType(DIFile *File,
                       ^
/home/jingpeng_wu/julia/usr/include/llvm/IR/DIBuilder.h:383:23: note:   candidate expects 3 arguments, 1 provided
/home/jingpeng_wu/julia/src/codegen.cpp: In function ‘void init_julia_llvm_env(llvm::Module*)’:
/home/jingpeng_wu/julia/src/codegen.cpp:5581:46: error: no matching function for call to ‘llvm::DIBuilder::createSubroutineType(llvm::DITypeRefArray)’
         dbuilder.getOrCreateTypeArray(diargs));
                                              ^
In file included from /home/jingpeng_wu/julia/src/codegen.cpp:46:0:
/home/jingpeng_wu/julia/usr/include/llvm/IR/DIBuilder.h:383:23: note: candidate: llvm::DISubroutineType* llvm::DIBuilder::createSubroutineType(llvm::DIFile*, llvm::DITypeRefArray, unsigned int)
     DISubroutineType *createSubroutineType(DIFile *File,
                       ^
/home/jingpeng_wu/julia/usr/include/llvm/IR/DIBuilder.h:383:23: note:   candidate expects 3 arguments, 1 provided
    LINK src/flisp/libflisp.a
    LINK src/flisp/flisp
In file included from /home/jingpeng_wu/julia/src/codegen.cpp:190:0:
/home/jingpeng_wu/julia/src/jitlayers.cpp: In instantiation of ‘void addOptimizationPasses(T*) [with T = llvm::legacy::FunctionPassManager]’:
/home/jingpeng_wu/julia/src/codegen.cpp:6132:30:   required from here
/home/jingpeng_wu/julia/src/jitlayers.cpp:25:41: error: ‘createTypeBasedAAWrapperPass’ was not declared in this scope
     PM->add(createTypeBasedAAWrapperPass());
                                         ^
/home/jingpeng_wu/julia/src/jitlayers.cpp:31:41: error: ‘createBasicAAWrapperPass’ was not declared in this scope
         PM->add(createBasicAAWrapperPass());
                                         ^
    FLISP src/julia_flisp.boot
    FLISP src/julia_flisp.boot.inc
    CC src/ast.o
Makefile:98: recipe for target 'codegen.o' failed
make[1]: *** [codegen.o] Error 1
Makefile:87: recipe for target 'julia-src-release' failed
make: *** [julia-src-release] Error 2
```

**Comment by jingpengwu** [comment]
Previous error was got from Ubuntu 15.10. I tried to compile in a ubuntu 14.04 machine and got a success. But I encountered another error while building the Cxx with `Pkg.build("Cxx")` in julia. The error is as follows:

```
julia> Pkg.build("Cxx")
INFO: Building Cxx
Tuning for julia installation at: /usr/people/jingpeng/workspace/julia/usr/bin
    CC /usr/people/jingpeng/.julia/v0.5/Cxx/deps/build/bootstrap.o
../src/bootstrap.cpp: In function ‘void* ActOnStartNamespaceDef(CxxInstance*, char*)’:
../src/bootstrap.cpp:815:7: error: no matching function for call to ‘clang::Sema::ActOnStartNamespaceDef(clang::Scope*, clang::SourceLocation, clang::SourceLocation, clang::SourceLocation, clang::IdentifierInfo*, clang::SourceLocation, clang::AttributeList*)’
       );
       ^
../src/bootstrap.cpp:815:7: note: candidate is:
In file included from /usr/people/jingpeng/workspace/julia/usr/bin/../../usr/include/clang/Parse/Parser.h:24:0,
                 from ../src/bootstrap.cpp:35:
/usr/people/jingpeng/workspace/julia/usr/bin/../../usr/include/clang/Sema/Sema.h:4095:9: note: clang::Decl* clang::Sema::ActOnStartNamespaceDef(clang::Scope*, clang::SourceLocation, clang::SourceLocation, clang::SourceLocation, clang::IdentifierInfo*, clang::SourceLocation, clang::AttributeList*, clang::UsingDirectiveDecl*&)
   Decl *ActOnStartNamespaceDef(Scope *S, SourceLocation InlineLoc,
         ^
/usr/people/jingpeng/workspace/julia/usr/bin/../../usr/include/clang/Sema/Sema.h:4095:9: note:   candidate expects 8 arguments, 7 provided
../src/bootstrap.cpp: In function ‘void* CreateTemplateParameterList(CxxInstance*, clang::NamedDecl**, size_t)’:
../src/bootstrap.cpp:2216:160: error: no matching function for call to ‘clang::TemplateParameterList::Create(clang::ASTContext&, clang::SourceLocation, clang::SourceLocation, clang::NamedDecl**&, size_t&, clang::SourceLocation)’
   return (void*)clang::TemplateParameterList::Create(Cxx->CI->getASTContext(), clang::SourceLocation(), clang::SourceLocation(), D, ND, clang::SourceLocation());
                                                                                                                                                                ^
../src/bootstrap.cpp:2216:160: note: candidate is:
In file included from /usr/people/jingpeng/workspace/julia/usr/bin/../../usr/include/clang/AST/DeclFriend.h:19:0,
                 from /usr/people/jingpeng/workspace/julia/usr/bin/../../usr/include/clang/AST/RecursiveASTVisitor.h:22,
                 from ../src/bootstrap.cpp:38:
/usr/people/jingpeng/workspace/julia/usr/bin/../../usr/include/clang/AST/DeclTemplate.h:74:33: note: static clang::TemplateParameterList* clang::TemplateParameterList::Create(const clang::ASTContext&, clang::SourceLocation, clang::SourceLocation, llvm::ArrayRef<clang::NamedDecl*>, clang::SourceLocation)
   static TemplateParameterList *Create(const ASTContext &C,
                                 ^
/usr/people/jingpeng/workspace/julia/usr/bin/../../usr/include/clang/AST/DeclTemplate.h:74:33: note:   candidate expects 5 arguments, 6 provided
make: *** [build/bootstrap.o] Error 1
=================================[ ERROR: Cxx ]=================================

LoadError: failed process: Process(`make -f BuildBootstrap.Makefile JULIA_HOME=/usr/people/jingpeng/workspace/julia/usr/bin`, ProcessExited(2)) [2]
while loading /usr/people/jingpeng/.julia/v0.5/Cxx/deps/build.jl, in expression starting on line 16

================================================================================

==============================================================================================[ BUILD ERRORS ]===============================================================================================

WARNING: Cxx had build errors.

 - packages with build errors remain installed in /usr/people/jingpeng/.julia/v0.5
 - build the package(s) and all dependencies with `Pkg.build("Cxx")`
 - build a single package by running its `deps/build.jl` script

=============================================================================================================================================================================================================

```

**Comment by tkelman** [comment]
I also see an undefined reference to `pthread_create` building Julia master against LLVM svn, https://travis-ci.org/JuliaLang/julia/jobs/102021742

**Comment by Keno** [comment]
The supported configuration at the moment is Julia 0.5 with LLVM 3.7.1. I have tested that that configuration works fine. If you run into any issues with that, please file a new issue.
