### ISSUE TITLE
Latest nightly build failure

### ISSUE THREAD

**Issue by wbhart** [Keno/Cxx.jl#20]
We tried to build CXX with the latest Julia-0.4 nightly on Ubuntu 12.04 with gcc-4.8.

```
julia> Pkg.build()
INFO: Building CXX
Tuning for julia installation at: /home/wbhart/julia/usr/bin
    CC /home/wbhart/.julia/v0.4/CXX/deps/build/bootstrap.o
../src/bootstrap.cpp:14:30: fatal error: llvm/IR/ValueMap.h: No such file or directory
 #include "llvm/IR/ValueMap.h"
                              ^
compilation terminated.
make: *** [build/bootstrap.o] Error 1
=================================[ ERROR: CXX ]=================================

failed process: Process(`make -f BuildBootstrap.Makefile JULIA_HOME=/home/wbhart/julia/usr/bin`, ProcessExited(2)) [2]
while loading /home/wbhart/.julia/v0.4/CXX/deps/build.jl, in expression starting on line 16

================================================================================
```

It looks like the LLVM file it is looking for no longer exists in the LLVM that Julia-0.4 uses.

[We tried building CXX with Julia-0.3 but it was looking for a source tree for Julia (starting from JULIA_HOME) but we had a binary installation of Julia 0.3 only. Should CXX work with Julia-0.3 with a source build? Or are you targeting Julia 0.4.]
